# syntax=docker/dockerfile:1
FROM polymerized
# ENV HOSTNAME=polymerized
# ENV DEV_COLOR=35
# = = = = = = = = = = = = = = = = = = = = =

# = = = = = = = = = = = = = = = = = = = = =
ENTRYPOINT ["/bin/bash"]