# syntax=docker/dockerfile:1
FROM polymerized
# = = = = = = = = = = = = = = = = = = = = =
ENV HOSTNAME=rust
ENV DEV_COLOR=31
# = = = = = = = = = = = = = = = = = = = = =

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# = = = = = = = = = = = = = = = = = = = = =
ENTRYPOINT ["/bin/bash"]